[build]
target = "riscv32imac_ch32h417.json"

[unstable]
build-std = ["core"]
json-target-spec = true

[target.riscv32imac_ch32h417]
rustflags = ["-C", "link-arg=-Tmemory.x"]
runner = ["py", "run.py"]
